# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r: release
latex: false
dist: bionic #Ubuntu 18.04 (Bionic Beaver)
osx_image: xcode12.2 #macOS 10.15.7
sudo: false
cache: packages
#addons:
#  apt:
#    packages:
#      - libfribidi-dev
#      - libgdal-dev
#      - libharfbuzz-dev
#      - libjq-dev
#      - libprotobuf-dev
#      - libsecret-1-dev
#      - libsodium-dev
#      - libudunits2-dev
#      - libv8-3.14-dev
#      - protobuf-compiler
brew_packages:
  - udunits
apt_packages:
  - libgdal-dev
r_binary_packages:
  - ps
  - R6
  - processx
  - Rcpp
  - cpp11
  - wk
  - proxy
  - e1071
  - magrittr
  - rlang
  - later
  - promises
  - colorspace
  - glue
  - systemfonts
  - utf8
  - crayon
  - cli
  - vctrs
  - pkgconfig
  - pillar
  - fansi
  - ellipsis
  - RColorBrewer
  - munsell
  - lifecycle
  - labeling
  - farver
  - withr
  - tibble
  - scales
  - isoband
  - gtable
  - digest
  - gridExtra
  - ggplot2
  - viridisLite
  - mime
  - xfun
  - fastmap
  - base64enc
  - lazyeval
  - jsonlite
  - htmltools
  - units
  - s2
  - DBI
  - classInt
  - terra
  - sp
  - yaml
  - leaflet.providers
  - viridis
  - raster
  - png
  - markdown
  - htmlwidgets
  - crosstalk
  - sfheaders
  - rapidjsonr
  - jsonify
  - geometries
  - callr
  - httpuv
  - plyr
  - uuid
  - svglite
  - sf
  - brew
  - leaflet
  - geojsonsf
  - webshot
  - servr
  - satellite
  - leafpop
  - leafem
  - rematch2
  - diffobj
  - rstudioapi
  - rprojroot
  - desc
  - stringi
  - stringr
  - highr
  - evaluate
  - jquerylib
  - tinytex
  - knitr
  - cachem
  - brio
  - purrr
  - sys
  - askpass
  - openssl
  - curl
  - V8
  - triebeard
  - httpcode
  - urltools
  - waldo
  - praise
  - pkgload
  - xml2
  - commonmark
  - whisker
  - rmarkdown
  - memoise
  - httr
  - fs
  - BH
  - RcppEigen
  - tidyselect
  - polyclip
  - tweenr
  - rex
  - rappdirs
  - filelock
  - sodium
  - assertthat
  - jsonvalidate
  - crul
  - testthat
  - roxygen2
  - lwgeom
  - googlePolylines
  - ggforce
  - covr
  - geojsonlint

os:
  - osx
  - linux

after_success:
  - test $TRAVIS_OS_NAME = "osx" && Rscript -e 'covr::codecov()'
  - test $TRAVIS_OS_NAME = "osx" && R CMD INSTALL . && Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: docs
  on:
    branch: master
    condition: $TRAVIS_OS_NAME = "osx"
